export default {
  CREATEOFFLINELOG: 'CREATEOFFLINELOG',
  UPDATELOGOFFLINE: 'UPDATELOGOFFLINE',
  CREATEUSEROFFLINE: 'CREATEUSEROFFLINE',
  UPDATEUSEROFFLINE: 'UPDATEUSEROFFLINE',
  UPDATEUSERSTATUSOFFLINE: 'UPDATEUSERSTATUSOFFLINE',
  CREATEENTRYOFFLINE: 'CREATEENTRYOFFLINE',
  CREATENOTEOFFLINE: 'CREATENOTEOFFLINE',

  RESETOFFLINESTORAGE: 'RESETOFFLINESTORAGE',
};
