export const statesDropdownArray = [
  { value: "AL" },
  { value: "AK" },
  { value: "AZ" },
  { value: "AR" },
  { value: "CA" },
  { value: "CO" },
  { value: "CT" },
  { value: "DE" },
  { value: "FL" },
  { value: "GA" },
  { value: "HI" },
  { value: "ID" },
  { value: "IL" },
  { value: "IN" },
  { value: "IA" },
  { value: "KS" },
  { value: "KY" },
  { value: "LA" },
  { value: "ME" },
  { value: "MD" },
  { value: "MA" },
  { value: "MI" },
  { value: "MN" },
  { value: "MS" },
  { value: "MO" },
  { value: "MT" },
  { value: "NE" },
  { value: "NV" },
  { value: "NH" },
  { value: "NJ" },
  { value: "NM" },
  { value: "NY" },
  { value: "NC" },
  { value: "ND" },
  { value: "OH" },
  { value: "OK" },
  { value: "OR" },
  { value: "PA" },
  { value: "RI" },
  { value: "SC" },
  { value: "SD" },
  { value: "TN" },
  { value: "TX" },
  { value: "UT" },
  { value: "VT" },
  { value: "VA" },
  { value: "WA" },
  { value: "WV" },
  { value: "WI" },
  { value: "WY" },
];

export const fecCitiesDropdownArray = [
  { value: "Dodge Island Lead" },
  { value: "K-Branch" },
  { value: "Main Line" },
  { value: "Port Lead" },
  { value: "Other" },
];

export const BNFSDivisions = [
  { value: "California" },
  { value: "Chicago" },
  { value: "Heartland" },
  { value: "Kansas" },
  { value: "Montana" },
  { value: "Northwest" },
  { value: "Powder River" },
  { value: "Red River" },
  { value: "Southwest" },
  { value: "Twin Cities" },
];

export const BNFSSubDivisions = {
  California: [
    { value: "Bakersfield" },
    { value: "Cajon" },
    { value: "Harbor" },
    { value: "Lucerne Valley" },
    { value: "Mojave" },
    { value: "Needles" },
    { value: "Olive" },
    { value: "Riverbank" },
    { value: "San Bernardino" },
    { value: "San Diego" },
    { value: "Stockton" },
  ],
  Chicago: [
    { value: "Aurora" },
    { value: "Barstow" },
    { value: "Beardstown" },
    { value: "Brookfield" },
    { value: "Cameron Connection" },
    { value: "Chicago" },
    { value: "Chillicothe" },
    { value: "Des Moines" },
    { value: "Fox River" },
    { value: "Graham Cutoff" },
    { value: "Marceline" },
    { value: "Mendota" },
    { value: "Ottumwa" },
    { value: "Peoria" },
    { value: "Rockford" },
    { value: "St Croix" },
    { value: "Thomas Hill" },
    { value: "Yates City" },
  ],
  Heartland: [
    { value: "Afton" },
    { value: "Amory" },
    { value: "Bayard" },
    { value: "Bellwood" },
    { value: "Birmingham" },
    { value: "Brookfield" },
    { value: "Cherokee" },
    { value: "Council Bluffs" },
    { value: "Creston" },
    { value: "Cuba" },
    { value: "Ft Scott" },
    { value: "Giltner" },
    { value: "Hannibal" },
    { value: "Napier" },
    { value: "Omaha" },
    { value: "Ottumwa" },
    { value: "Ravenna" },
    { value: "River" },
    { value: "St Joseph" },
    { value: "Thayer North" },
    { value: "Thayer South" },
  ],
  Kansas: [
    { value: "Arkansas City" },
    { value: "Boise City" },
    { value: "Borger" },
    { value: "Dalhart" },
    { value: "Douglass" },
    { value: "Emporia" },
    { value: "Hereford" },
    { value: "La Junta" },
    { value: "Panhandle" },
    { value: "Raton" },
    { value: "Red River Valley" },
    { value: "Strong City" },
    { value: "Topeka" },
    { value: "Twin Peaks" },
    { value: "Wut Wichita Union Term" },
  ],
  Montana: [
    { value: "Big Sandy" },
    { value: "Broadview" },
    { value: "Choteau" },
    { value: "Circle" },
    { value: "Colstrip" },
    { value: "Copper City" },
    { value: "Crosby" },
    { value: "Dickinson" },
    { value: "Fairfield" },
    { value: "Forsyth" },
    { value: "Fort Benton" },
    { value: "Glasgow" },
    { value: "Great Falls" },
    { value: "Grenora" },
    { value: "Hettinger" },
    { value: "Hi Line" },
    { value: "Kalispell" },
    { value: "Ko" },
    { value: "Kootenai River" },
    { value: "Laurel" },
    { value: "Lewistown" },
    { value: "Logan   Butte" },
    { value: "Milk River" },
    { value: "Mobridge" },
    { value: "Newcomb Branch" },
    { value: "Niobe" },
    { value: "Sarpy Line" },
    { value: "Scobey" },
    { value: "Sidney Line" },
    { value: "Sweetgrass" },
    { value: "Valier" },
  ],
  Northwest: [
    { value: "Bellingham" },
    { value: "Burbank" },
    { value: "Cherry Point" },
    { value: "Coeur D Alene" },
    { value: "Columbia River" },
    { value: "Fallbridge" },
    { value: "Gateway" },
    { value: "Kettle Falls" },
    { value: "Lakeside" },
    { value: "Lakeview" },
    { value: "New Westminster" },
    { value: "Oregon Trunk" },
    { value: "Palouse" },
    { value: "Scenic" },
    { value: "Seattle" },
    { value: "Spokane" },
    { value: "Stampede" },
    { value: "Sumas" },
    { value: "Tilbury Island Spur" },
    { value: "Yakima Valley" },
  ],
  "Powder River": [
    { value: "Akron" },
    { value: "Angora" },
    { value: "Beatrice" },
    { value: "Big Horn" },
    { value: "Black Hills" },
    { value: "Brush" },
    { value: "Butte" },
    { value: "Campbell" },
    { value: "Canyon" },
    { value: "Casper" },
    { value: "Cobb Line" },
    { value: "Cody" },
    { value: "Denver Freight Main" },
    { value: "Denver Passenger Main" },
    { value: "Dutch" },
    { value: "Front Range" },
    { value: "Golden" },
    { value: "Hastings" },
    { value: "Imperial" },
    { value: "Lester" },
    { value: "Moran Jct Jones Jct" },
    { value: "Orin" },
    { value: "Pikes Peak" },
    { value: "Pueblo" },
    { value: "Reno" },
    { value: "Sand Hills" },
    { value: "Spanish Peaks" },
    { value: "Valley" },
    { value: "Wymore" },
  ],
  "Red River": [
    { value: "Arkansas City" },
    { value: "Avard" },
    { value: "Bay City" },
    { value: "Chickasha" },
    { value: "Conroe" },
    { value: "Creek" },
    { value: "Dfw" },
    { value: "Dimmitt Spur" },
    { value: "Dobbin Conn Track" },
    { value: "Ft Worth" },
    { value: "Galveston" },
    { value: "Houston" },
    { value: "Lafayette" },
    { value: "Lampasas" },
    { value: "Longview" },
    { value: "Madill" },
    { value: "Mykawa" },
    { value: "New South Yd  Tx" },
    { value: "Plainview" },
    { value: "Red River Valley" },
    { value: "Red Rock" },
    { value: "Seadrift" },
    { value: "Silsbee" },
    { value: "Slaton" },
    { value: "Sooner" },
    { value: "Up  Old South Yd" },
    { value: "Venus" },
    { value: "Wichita Falls" },
  ],
  Southwest: [
    { value: "Carlsbad" },
    { value: "Clovis" },
    { value: "Coronado" },
    { value: "Defiance" },
    { value: "El Paso" },
    { value: "Ennis" },
    { value: "Gallup" },
    { value: "Glorieta" },
    { value: "Hereford" },
    { value: "Lee Ranch" },
    { value: "Mines" },
    { value: "Phoenix" },
    { value: "Seligman" },
  ],
  "Twin Cities": [
    { value: "Aberdeen" },
    { value: "Allouez" },
    { value: "Appleton" },
    { value: "Brainerd" },
    { value: "Browns Valley" },
    { value: "Canton" },
    { value: "Casco" },
    { value: "Clifford Line" },
    { value: "Corson" },
    { value: "Devils Lake" },
    { value: "Drayton" },
    { value: "Glasston" },
    { value: "Grand Forks" },
    { value: "Hanley Falls" },
    { value: "Hannah" },
    { value: "Hib Tac" },
    { value: "Hillsboro" },
    { value: "Hinckley" },
    { value: "Jamestown" },
    { value: "Ko" },
    { value: "Lakes" },
    { value: "Lst T  Superior  Wi" },
    { value: "Madison" },
    { value: "Marshall" },
    { value: "Mayville" },
    { value: "Midway" },
    { value: "Mitchell" },
    { value: "Monticello" },
    { value: "Moorhead" },
    { value: "Morris" },
    { value: "Noyes" },
    { value: "Oneill" },
    { value: "Prosper" },
    { value: "Rolla" },
    { value: "Sioux City" },
    { value: "St Cloud Collegeville" },
    { value: "St Croix" },
    { value: "St Paul" },
    { value: "Staples" },
    { value: "Warwick" },
    { value: "Watertown" },
    { value: "Wayzata" },
    { value: "Westhope" },
    { value: "Zap Line" },
  ],
};

export const UPDivisions = [
  { value: "Alton & Southern" },
  { value: "Chicago" },
  { value: "Commuter Operations" },
  { value: "Great Lakes" },
  { value: "Great Plains" },
  { value: "Gulf Coast" },
  { value: "Heartland" },
  { value: "Houston" },
  { value: "Los Angeles" },
  { value: "Mid America" },
  { value: "Northern California" },
  { value: "Pacific Northwest" },
  { value: "Rocky Mountain" },
  { value: "South Texas" },
  { value: "Texoma" },
];

export const UPSubDivisions = {
  "Rocky Mountain": [
    { value: "Aberdeen" },
    { value: "Blue Diamond Spur" },
    { value: "Bmi" },
    { value: "Cache Valley" },
    { value: "Caliente" },
    { value: "Cane Creek" },
    { value: "Castle Valley Ind Ld" },
    { value: "Cedar City" },
    { value: "Chevron Ind Ld" },
    { value: "Cima" },
    { value: "Conda Lead" },
    { value: "Craig" },
    { value: "Craig Ind Ld" },
    { value: "Cumberland Ind Ld" },
    { value: "Denver Rock Island Lead" },
    { value: "Dolomite Lead" },
    { value: "Dry Valley" },
    { value: "Eagle Valley Ind Ld" },
    { value: "Elkol Ind Ld" },
    { value: "Ellerbeck Ind Ld" },
    { value: "Empire Ind Ld" },
    { value: "Energy Line" },
    { value: "Evanston" },
    { value: "Glenwood Springs" },
    { value: "Green River" },
    { value: "Hill Field Ind Ld" },
    { value: "Ipp Ind Ld" },
    { value: "Jim Bridger Ind Ld" },
    { value: "Lakeside" },
    { value: "Laramie" },
    { value: "Las Vegas Ind Park Ind Ld" },
    { value: "Lynndyl" },
    { value: "Malad" },
    { value: "Mead Lake" },
    { value: "Moffat Tunnel" },
    { value: "Montana" },
    { value: "Montrose Ind Ld" },
    { value: "Nampa" },
    { value: "Nellis Ind Ld" },
    { value: "North Fork" },
    { value: "Ogden" },
    { value: "Parachute Ind Ld" },
    { value: "Pleasant Valley" },
    { value: "Pocatello" },
    { value: "Provo" },
    { value: "Provo Ind Ld" },
    { value: "Ramsey Ind Ld" },
    { value: "Rawlins" },
    { value: "Reliance Spur" },
    { value: "Rocky Flats Ind Ld" },
    { value: "Rowley Ind Ld" },
    { value: "Russina Spur" },
    { value: "Salt Lake" },
    { value: "Salt Lake Center (SL)" },
    { value: "Salt Lake Center Ind Ld" },
    { value: "Salt Lake Old Passngr Main" },
    { value: "Scoville" },
    { value: "Scoville (ABANDONED)" },
    { value: "Shafter" },
    { value: "Sharp" },
    { value: "Solvay Ind Ld" },
    { value: "South Pass Ind Ld" },
    { value: "Stauffer Ind Ld" },
    { value: "Sunnyside Ind Ld" },
    { value: "Sweetwater #1 Spur" },
    { value: "Syracuse Ind Ld" },
    { value: "Texas Gulf Soda Ind Ld" },
    { value: "Tintic Ind Ld" },
    { value: "Ute Ind Ld" },
    { value: "Utip Ind Ld" },
    { value: "Warner Spur" },
    { value: "Woods Cross Ind Ld" },
  ],
  Chicago: [
    { value: "Adams" },
    { value: "Beloit Ind Ld" },
    { value: "Belvidere" },
    { value: "Blue Island (CSX)" },
    { value: "Chemung Ind Ld" },
    { value: "Chicago Heights Ind Ld" },
    { value: "Clyman" },
    { value: "Cragin Lead" },
    { value: "Edgewater Ind Ld" },
    { value: "Evansville Ind Ld" },
    { value: "Farm Ind Ld" },
    { value: "Geneva" },
    { value: "Granville Ind Ld" },
    { value: "Harvard" },
    { value: "Haven Ind Ld" },
    { value: "Ingalton Ind Ld" },
    { value: "Janesville Ind Ld" },
    { value: "Joliet" },
    { value: "Joliet (CN)" },
    { value: "Joliet Intermodal Terminal" },
    { value: "Kd Ind Ld" },
    { value: "Kenosha" },
    { value: "Kohler Ind Ld" },
    { value: "Lake" },
    { value: "Milwaukee" },
    { value: "National Ave Ind Ld" },
    { value: "Peoria" },
    { value: "Peoria - Adams St Lead" },
    { value: "Plaines Ind Ld" },
    { value: "Proviso Yard" },
    { value: "Rockford Ind Ld" },
    { value: "Rockwell" },
    { value: "Seeger Live Wye" },
    { value: "Shoreline" },
    { value: "St. Charles Ind Ld" },
    { value: "State Line Ind Ld" },
    { value: "Troy Grove" },
    { value: "Villa Grove" },
    { value: "Waukesha Ind Ld" },
    { value: "West Chicago Yard" },
  ],
  "Great Lakes": [
    { value: "Adams" },
    { value: "Agp (OLD THORNTON) LEAD" },
    { value: "Albert Lea" },
    { value: "Alden Ind Ld" },
    { value: "Altoona" },
    { value: "Ankeny Ind Ld" },
    { value: "Ankeny Ind Ld (ABANDONED)" },
    { value: "Blair" },
    { value: "Bondurant Ind Ld" },
    { value: "Boone" },
    { value: "Camp Douglas Ind Ld" },
    { value: "Cargill Ind Ld" },
    { value: "Cedar Rapids Ind Ld" },
    { value: "Cedar Rapids North Yard" },
    { value: "Chippewa Falls" },
    { value: "Chippewa Falls (LEASED PROG)" },
    { value: "Clinton" },
    { value: "Columbus" },
    { value: "Cowboy Spur" },
    { value: "Crete Lead" },
    { value: "Dakota City Ind Ld" },
    { value: "Dows Ind Ld" },
    { value: "Eagle Grove Ind Ld" },
    { value: "Estherville" },
    { value: "Fairmont" },
    { value: "Falls City" },
    { value: "Farnhamville Ind Ld" },
    { value: "Fort Dodge" },
    { value: "Fort Dodge Ind Ld" },
    { value: "Geneva" },
    { value: "Gilmore Ind Ld" },
    { value: "Golden Valley Ind Ld" },
    { value: "Gypsum Lead" },
    { value: "Highland Park Ind Ld" },
    { value: "Hollingsworth Ind Ld" },
    { value: "Hull Ave Ind Ld" },
    { value: "Jefferson Jct. Lead" },
    { value: "Jewell" },
    { value: "Kanawha Ind Ld" },
    { value: "Kearney" },
    { value: "Lake Mills Ind Ld" },
    { value: "Laurens" },
    { value: "Lincoln" },
    { value: "Mankato" },
    { value: "Mankato East Ind Ld" },
    { value: "Mankato West Ind Ld" },
    { value: "Mason City" },
    { value: "Mason City Ind Ld" },
    { value: "Menomonie Lead" },
    { value: "Midway (BNSF)" },
    { value: "Millard Ind Ld" },
    { value: "Montgomery" },
    { value: "Norfolk Spur" },
    { value: "North Omaha Lead" },
    { value: "Nsp Lead" },
    { value: "Omaha" },
    { value: "Oskaloosa" },
    { value: "Oskaloosa Lead" },
    { value: "Perry" },
    { value: "Rake" },
    { value: "Rock Island Ind Ld" },
    { value: "Rockwell Ind Ld" },
    { value: "Roelyn Ind Ld" },
    { value: "Roseport Ind Ld" },
    { value: "Sergeant Bluff Ind Ld" },
    { value: "Sibley Spur" },
    { value: "Sioux City" },
    { value: "State Street Ind Ld" },
    { value: "Stillwater Ind Ld" },
    { value: "Superior Ind Ld" },
    { value: "Swanwood Lead" },
    { value: "Tara" },
    { value: "Trenton" },
    { value: "Twelfth St. Lead C.Bluffs" },
    { value: "Waukee Ind Ld" },
    { value: "Wimmer Wye" },
    { value: "Winona" },
    { value: "Worthington" },
  ],
  "Mid America": [
    { value: "Airline Ind Ld" },
    { value: "Alton (NS)" },
    { value: "Alton Ind Ld" },
    { value: "Bastrop Ind Ld" },
    { value: "Beardstown (BNSF-PAL)" },
    { value: "Bonham Ind Ld" },
    { value: "Bonne Terre Ind Ld" },
    { value: "Brinkley" },
    { value: "Broadway Ind Ld" },
    { value: "Cadet Ind Ld" },
    { value: "Captain Mine Lead" },
    { value: "Carlisle Lead" },
    { value: "Chester" },
    { value: "Church Ind Ld" },
    { value: "Commerce Ind Ld" },
    { value: "Conway Ind Ld" },
    { value: "Cotter Sub (LEASED MNA)" },
    { value: "Crystal City Ind Ld" },
    { value: "Desoto" },
    { value: "Dk&S Ind Ld" },
    { value: "Dowco Ind Ld" },
    { value: "Eads Sub (TRRA)" },
    { value: "El Dorado" },
    { value: "Fort Gibson-Oge Spur" },
    { value: "Georgia St. Ind Ld" },
    { value: "Good Roads Lead" },
    { value: "Granite City Ind Ld" },
    { value: "Gurdon Ind Ld" },
    { value: "Havana Spur" },
    { value: "Helena" },
    { value: "Hot Springs Ind Ld" },
    { value: "Hoxie" },
    { value: "Hulbert" },
    { value: "Jacksonville Afb Ind Ld" },
    { value: "Jefferson City" },
    { value: "Joliet" },
    { value: "Jonesboro" },
    { value: "Jsw Ind Ld" },
    { value: "Junction Bridge Line" },
    { value: "Kellogg Ind Ld" },
    { value: "Kirkwood Lead" },
    { value: "Koppers Spur" },
    { value: "Labadie Ind Ld" },
    { value: "Lake Ind Ld" },
    { value: "Lesperance Ind Ld" },
    { value: "Little Rock" },
    { value: "Little Rock Conn (ABANDONED)" },
    { value: "Lufkin" },
    { value: "Macarthur Bridge (TRRA)" },
    { value: "Malden Ind Ld" },
    { value: "Marion" },
    { value: "Mcgehee" },
    { value: "Memphis" },
    { value: "Merchants Sub (TRRA)" },
    { value: "Mineola" },
    { value: "Monroe" },
    { value: "Monroe City Lead" },
    { value: "Monsanto @Hoffman Ld" },
    { value: "Monterey" },
    { value: "Mt. Vernon" },
    { value: "Nashville" },
    { value: "New Madrid" },
    { value: "North Memphis Lead" },
    { value: "Palestine" },
    { value: "Pana" },
    { value: "Paragould Lead" },
    { value: "Pequot Ind Ld" },
    { value: "Pinckneyville" },
    { value: "Pine Bluff" },
    { value: "Pulaski Lead" },
    { value: "Reisor" },
    { value: "Rock Street Ind Ld" },
    { value: "Salem" },
    { value: "Shreveport" },
    { value: "Shreveport Ind Ld" },
    { value: "Sikeston" },
    { value: "Southwestern Electrical Spur" },
    { value: "Sparta" },
    { value: "Springfield" },
    { value: "Stallings Lead" },
    { value: "Ste. Genevieve Ind Ld" },
    { value: "Stuttgart Ind Ld" },
    { value: "Tenark Ind Ld" },
    { value: "Tolson Ind Ld" },
    { value: "Van Buren" },
    { value: "Villa Grove" },
    { value: "Wagoner" },
    { value: "Westville Ind Ld" },
    { value: "White Bluff" },
    { value: "White Bluff Ind Ld" },
    { value: "Wynne" },
  ],
  "Los Angeles": [
    { value: "Alameda Corridor" },
    { value: "Alameda Corridor (PHL)" },
    { value: "Alameda Ind Ld" },
    { value: "Alhambra" },
    { value: "Alhambra Ind Ld" },
    { value: "Anamax Mine Spur" },
    { value: "Asarco Lead" },
    { value: "Azusa Ind Ld" },
    { value: "Brea Chem Ind Ld" },
    { value: "Calexico" },
    { value: "Carson Lead" },
    { value: "Chandler Ind Ld" },
    { value: "Chino Ind Ld" },
    { value: "Cima" },
    { value: "City Of Industry Lead" },
    { value: "Clifton Ind Ld" },
    { value: "Crestmore Ind Ld" },
    { value: "Cyprus Mine Spur" },
    { value: "Declezville Ind Ld" },
    { value: "Del Amo Ind Ld" },
    { value: "Dixon Spur" },
    { value: "Dolores Ind Ld" },
    { value: "El Centro" },
    { value: "El Segundo Ind Ld" },
    { value: "Fullerton Ind Ld" },
    { value: "Gila" },
    { value: "Holtville Ind Ld" },
    { value: "La Habra" },
    { value: "Lakewood Ind Ld" },
    { value: "Lompoc Ind Ld" },
    { value: "Lone Pine" },
    { value: "Lordsburg" },
    { value: "Los Angeles" },
    { value: "Los Nietos" },
    { value: "Manuel (PHL)" },
    { value: "Mesquite Line" },
    { value: "Mojave" },
    { value: "Montalvo Ind Ld" },
    { value: "Nogales" },
    { value: "Oak Creek Ind Ld" },
    { value: "Paramount Ind Ld" },
    { value: "Patata Ind Ld" },
    { value: "Phoenix" },
    { value: "River East Bank (SCAX)" },
    { value: "Riverside Ind Ld" },
    { value: "Rohr Ind Ld" },
    { value: "Roll Ind Ld" },
    { value: "San Bernardino (BNSF)" },
    { value: "San Gabriel (SCAX)" },
    { value: "San Pedro" },
    { value: "Santa Ana Ind Ld" },
    { value: "Santa Barbara" },
    { value: "Stanton Ind Ld" },
    { value: "Tempe Ind Ld" },
    { value: "Torrance Ind Ld" },
    { value: "Tustin Ind Ld" },
    { value: "Ventura (SCAX)" },
    { value: "White Hills Ind Ld" },
    { value: "Wilmington" },
    { value: "Yuma" },
  ],
  "Great Plains": [
    { value: "Alamosa (SLRG)" },
    { value: "Boettcher Ind Ld" },
    { value: "Boulder Ind Ld" },
    { value: "Burnham Lead" },
    { value: "Casper Ind Ld" },
    { value: "Colorado Springs" },
    { value: "Crandall Lead" },
    { value: "Fort Collins" },
    { value: "Fort Collins Ind Ld" },
    { value: "Fort Logan Spur" },
    { value: "Gerald Gentleman" },
    { value: "Greeley" },
    { value: "Hallam" },
    { value: "Hastings Utility Lead" },
    { value: "Julesburg" },
    { value: "Kearney" },
    { value: "Kearney Ind Ld" },
    { value: "Laramie" },
    { value: "Limon" },
    { value: "Marysville" },
    { value: "Moffat Tunnel" },
    { value: "Monfort Ind Ld" },
    { value: "North Platte Terminal" },
    { value: "Orin" },
    { value: "Pikes Peak (BNSF)" },
    { value: "Powder River" },
    { value: "River Ind Ld" },
    { value: "Sidney" },
    { value: "South Morrill" },
    { value: "South Torrington Ind Ld" },
    { value: "Templeton Gap Lead" },
    { value: "Tennessee Pass" },
    { value: "Walsenburg" },
    { value: "Yoder" },
  ],
  "Gulf Coast": [
    { value: "Alexandria" },
    { value: "Anchorage" },
    { value: "Angleton" },
    { value: "Avondale" },
    { value: "Avoyelles" },
    { value: "Baton Rouge Ind Ld" },
    { value: "Bayou Pierre Lead" },
    { value: "Beaumont" },
    { value: "Brownsville" },
    { value: "Camp Beauregard Ind Ld" },
    { value: "Celanese Ind Ld" },
    { value: "Chaison Spur" },
    { value: "Chocolate Bayou Ind Ld" },
    { value: "Coleto Creek" },
    { value: "Corpus Christi" },
    { value: "Cuero" },
    { value: "Dequincy" },
    { value: "Deridder Spur" },
    { value: "Dolet Hills Lead" },
    { value: "Dpc Spur" },
    { value: "Dupont Lead @Orange" },
    { value: "Freeport Ind Ld" },
    { value: "Harbor Ind Ld" },
    { value: "Harlingen" },
    { value: "Hearne" },
    { value: "Henderson Ind Ld" },
    { value: "Houston" },
    { value: "Jacksonville Ind Ld" },
    { value: "Kosmos Ind Ld" },
    { value: "Lafayette" },
    { value: "Lake Charles" },
    { value: "Lake Charles (ABANDONED)" },
    { value: "Lake Charles Ind Ld" },
    { value: "Letourneau Ind Ld" },
    { value: "Livonia" },
    { value: "Lufkin" },
    { value: "Monroe" },
    { value: "Olmito Ind Ld" },
    { value: "Orange Docks Lead" },
    { value: "Orange Ind Ld" },
    { value: "Oyster Creek Lead" },
    { value: "Palestine" },
    { value: "Palo Alto Ind Ld" },
    { value: "Phillips Refinery Ind Ld" },
    { value: "Port Arthur Lead" },
    { value: "Port Lavaca Ind Ld" },
    { value: "Reisor" },
    { value: "Rosebluff Spur" },
    { value: "Rosenberg" },
    { value: "Sabine Ind Ld" },
    { value: "Seadrift Ind Ld" },
    { value: "T&No Ind Ld" },
    { value: "Victoria Ind Ld" },
    { value: "Westbank Ind Ld" },
  ],
  "Alton & Southern": [
    { value: "Alton & Southern Gateway" },
    { value: "Cahokia Ind Ld (A&S)" },
  ],
  "Pacific Northwest": [
    { value: "American Can Spur" },
    { value: "Ayer" },
    { value: "Bend" },
    { value: "Black Butte" },
    { value: "Brooklyn" },
    { value: "Carty Ind Ld" },
    { value: "Cascade" },
    { value: "Coeur D'Alene Ind Ld" },
    { value: "Coos Bay Ind Ld" },
    { value: "Fairfield Ind Ld" },
    { value: "Heppner Lead" },
    { value: "Homedale Lead" },
    { value: "Huntington" },
    { value: "Idaho Northern Ind Ld" },
    { value: "Kalan Ind Ld" },
    { value: "Kenton Line" },
    { value: "La Grande" },
    { value: "Marcola Ind Ld" },
    { value: "Modoc" },
    { value: "Nampa" },
    { value: "New Meadows Lead" },
    { value: "Olympia Ind Ld" },
    { value: "Orchard Ind Ld" },
    { value: "Pilot Rock Ind Ld" },
    { value: "Portland" },
    { value: "Riparia Ind Ld" },
    { value: "Seattle" },
    { value: "Seattle (BNSF)" },
    { value: "Seattle 5th Ave Lead" },
    { value: "South Rivergate Ind Ld" },
    { value: "Spokane" },
    { value: "Spokane (BNSF)" },
    { value: "St. Johns Ind Ld" },
    { value: "Stoddard Lead" },
    { value: "Sumner Ind Ld" },
    { value: "Umatilla Ind Ld" },
    { value: "Wallace Ind Ld" },
    { value: "Willamette Bridge Line" },
    { value: "Yakima" },
  ],
  Houston: [
    { value: "Arco Ind Ld" },
    { value: "Barbours Cut Ind Ld" },
    { value: "Bayport Loop Ind Ld" },
    { value: "Baytown" },
    { value: "Beaumont" },
    { value: "Bell Line @Houston" },
    { value: "Booth Yard Ind Ld" },
    { value: "Bryan" },
    { value: "Cedar Bayou Ind Ld" },
    { value: "Clinton Ind Ld" },
    { value: "Columbia Tap Ind Ld" },
    { value: "Dart Ind Ld" },
    { value: "Eureka" },
    { value: "Galveston" },
    { value: "Galveston Island Lead" },
    { value: "Glass Track Ind Ld" },
    { value: "Glidden" },
    { value: "Harrisburg" },
    { value: "Hl&P Ind Ld" },
    { value: "Houston" },
    { value: "Houston East Belt" },
    { value: "Houston West Belt" },
    { value: "Huntsville Ind Ld" },
    { value: "Jacinto Port Lead" },
    { value: "Katy Eureka Ind Ld" },
    { value: "Lufkin" },
    { value: "Navasota" },
    { value: "Navigation Ind Ld" },
    { value: "Navigation Yard Lead" },
    { value: "Palestine" },
    { value: "Popp Ind Ld" },
    { value: "Seabrook Ind Ld" },
    { value: "Settegast Yard" },
    { value: "Sheldon Spur" },
    { value: "Spence Ind Ld" },
    { value: "Strang" },
    { value: "Sugarland Spur" },
    { value: "Texas City Ind Ld" },
    { value: "U.S. Steel Lead  Baytown" },
    { value: "Velsicol Ind Ld" },
  ],
  "South Texas": [
    { value: "Arenal Ind Ld" },
    { value: "Austin" },
    { value: "Bryan" },
    { value: "Camp Stanley (ABANDONED)" },
    { value: "Cline Mine Ind Ld" },
    { value: "Corpus Christi" },
    { value: "Cuero" },
    { value: "Del Rio" },
    { value: "Eagle Pass" },
    { value: "Ennis" },
    { value: "Ft. Worth" },
    { value: "Georgetown Ind Ld" },
    { value: "Giddings" },
    { value: "Glidden" },
    { value: "Hearne" },
    { value: "Jt Deeley Power Plant" },
    { value: "Kerrville" },
    { value: "Kerrville Ind Ld" },
    { value: "Laredo" },
    { value: "Lcra Lead" },
    { value: "Lockhart" },
    { value: "Longhorn Lead" },
    { value: "Navasota" },
    { value: "Old Austin Main @Giddings" },
    { value: "Rockport" },
    { value: "Salado Lead" },
    { value: "Sanderson" },
    { value: "Sealy Ind Ld" },
    { value: "Smithville" },
    { value: "Waco" },
  ],
  Heartland: [
    { value: "Arkansas City Ind Ld" },
    { value: "Atchison Ind Ld" },
    { value: "Bagnell Ind Ld" },
    { value: "Bestwall Ind Ld" },
    { value: "Carrizozo" },
    { value: "Cherokee" },
    { value: "Coffeyville" },
    { value: "Durand Lead" },
    { value: "El Reno Freight Line" },
    { value: "Enid" },
    { value: "Fairfax Lead" },
    { value: "Falls City" },
    { value: "Glen Park Yard" },
    { value: "Goodyear Lead @N.Topeka" },
    { value: "Herington" },
    { value: "Hiawatha" },
    { value: "Hope Ind Ld" },
    { value: "Jefferson City" },
    { value: "Jeffrey Spur" },
    { value: "K.C. Terminal (KCT)" },
    { value: "Kansas" },
    { value: "Kc Metro (BIG MARY)" },
    { value: "Kc Metro (COFFEYVILLE)" },
    { value: "Kc Metro (FALLS CITY)" },
    { value: "Kc Metro (KANSAS)" },
    { value: "Kc Metro (NEFF)" },
    { value: "Kc Metro (SHEEP JUMP)" },
    { value: "Limon" },
    { value: "Lost Springs" },
    { value: "Marshall Ind Ld" },
    { value: "Mcpherson Ind Ld" },
    { value: "New Strawn Lead" },
    { value: "Norkan Jct" },
    { value: "Oklahoma City" },
    { value: "Osawatomie Lead" },
    { value: "Parsons" },
    { value: "Pixley Ind Ld Independence" },
    { value: "Plainville Ind Ld" },
    { value: "Pratt" },
    { value: "River" },
    { value: "Robinson Ind Ld" },
    { value: "Salina" },
    { value: "Sedalia" },
    { value: "Sharon Springs" },
    { value: "Sid Ind Ld" },
    { value: "St. Joseph Ind Ld" },
    { value: "Topeka" },
    { value: "Trenton" },
    { value: "Trigo Ind Ld" },
    { value: "Tucumcari" },
    { value: "Wagoner" },
    { value: "Weeping Water Ind Ld" },
    { value: "Wichita Ind Ld" },
  ],
  Texoma: [
    { value: "Athens" },
    { value: "Baird" },
    { value: "Black Fox Power Plant" },
    { value: "Carrizozo" },
    { value: "Cherokee" },
    { value: "Choctaw" },
    { value: "Corsicana" },
    { value: "Dallas" },
    { value: "Dallas Belt Line" },
    { value: "Dfw" },
    { value: "Duncan" },
    { value: "Enid" },
    { value: "Ennis" },
    { value: "Fort Worth (BNSF)" },
    { value: "Ft. Bliss Ind Ld" },
    { value: "Ft. Worth" },
    { value: "Gatesville Ind Ld" },
    { value: "Great Southwest North" },
    { value: "Great Southwest South" },
    { value: "Hillsboro Ind Ld" },
    { value: "International Ind Ld" },
    { value: "Lawton" },
    { value: "Lawton Ind Ld" },
    { value: "Lordsburg" },
    { value: "Midlothian" },
    { value: "Mineola" },
    { value: "Muskogee Spur" },
    { value: "Pine Bluff" },
    { value: "Pryor Ind Ld" },
    { value: "Toyah" },
    { value: "Tulsa" },
    { value: "Tulsa Ind Ld" },
    { value: "Tyler Ind Ld" },
    { value: "Valentine" },
    { value: "Waco" },
    { value: "Wagoner" },
  ],
  "Northern California": [
    { value: "Benicia Lead" },
    { value: "Black Butte" },
    { value: "Canyon" },
    { value: "Chemurgic Lead" },
    { value: "Coast" },
    { value: "Elko" },
    { value: "Fallon Ind Ld" },
    { value: "Flanigan Ind Ld" },
    { value: "Fresno" },
    { value: "Granite Rock Ind Ld" },
    { value: "Holland Ind Ld" },
    { value: "Hollister Ind Ld" },
    { value: "Ione Ind Ld" },
    { value: "Lakeside" },
    { value: "Leareno Ind Ld" },
    { value: "Martinez" },
    { value: "Mather Lead" },
    { value: "Mchenry Ind Ld" },
    { value: "Milpitas Ind Ld" },
    { value: "Mina" },
    { value: "Modesto Lead" },
    { value: "Mojave" },
    { value: "Nevada" },
    { value: "Newark Ind Ld" },
    { value: "Niles" },
    { value: "North Madera Ind Ld" },
    { value: "North San Jose Ind Ld" },
    { value: "Oakdale Ind Ld" },
    { value: "Oakland" },
    { value: "Owens-Illinois Lead" },
    { value: "Pearson Ind Ld" },
    { value: "Placerville Ind Ld" },
    { value: "Port Chicago Ind Ld" },
    { value: "Redwood Harbor Ind Ld" },
    { value: "Redwood Jct Ind Ld" },
    { value: "Reno Ind Ld" },
    { value: "Roseville" },
    { value: "Sacramento" },
    { value: "San Francisco" },
    { value: "Santa Cruz Ind Ld" },
    { value: "Shafter" },
    { value: "Sierra Pacific Plant" },
    { value: "South San Francisco Lead" },
    { value: "Spreckels Ind Ld" },
    { value: "Tidewater Ind Ld" },
    { value: "Tracy" },
    { value: "Valley" },
    { value: "Vasona Ind Ld" },
    { value: "Warm Springs" },
    { value: "Winnemucca" },
    { value: "Woodbridge Ind Ld" },
    { value: "Woodland Spur" },
  ],
  "Commuter Operations": [
    { value: "Chicago Terminal Low Line" },
    { value: "Cragin Lead" },
    { value: "Crystal Lake Ind Ld" },
    { value: "Geneva" },
    { value: "Harvard" },
    { value: "Kenosha" },
    { value: "Mchenry" },
    { value: "Weber Lead" },
  ],
};

export const NSDivisions = [
  { value: "Blue Ridge" },
  { value: "Coastal" },
  { value: "Great Lakes" },
  { value: "Gulf" },
  { value: "Keystone" },
  { value: "Midwest" },
];

export const NSSubivisions = {
  "Blue Ridge": [
    { value: "Alexandria-Montview" },
    { value: "Altavista" },
    { value: "Appalachia" },
    { value: "Asheville-Flatrock" },
    { value: "Belews Creek Spur" },
    { value: "Ben Creek Spur" },
    { value: "Big Creek Branch" },
    { value: "Big Creek Spur" },
    { value: "Big Prater Spur" },
    { value: "Big Toms Creek Branch" },
    { value: "Blacksburg Branch" },
    { value: "Blue Ridge" },
    { value: "Bradshaw Spur" },
    { value: "Briar Mountain Branch" },
    { value: "Buchanan Branch" },
    { value: "Buckeye Branch" },
    { value: "CW District" },
    { value: "Calvin Spur" },
    { value: "Catawba" },
    { value: "Chocowinity-New Bern" },
    { value: "Christiansburg" },
    { value: "City Point Branch" },
    { value: "Clinch Valley Extension" },
    { value: "Clinch Valley" },
    { value: "Clover Spur" },
    { value: "Cloverdale Branch" },
    { value: "Coal Creek Branch" },
    { value: "Colmont Spur" },
    { value: "Columbus Terminal" },
    { value: "Columbus-Dayton" },
    { value: "Cub Creek Branch" },
    { value: "Delorme Branch" },
    { value: "Dismal Creek Branch" },
    { value: "Dixiana Branch" },
    { value: "Dry Fork Branch" },
    { value: "Dumps Creek Branch" },
    { value: "Durham" },
    { value: "Franklin" },
    { value: "Garden Creek Branch" },
    { value: "Gilbert Branch" },
    { value: "Glamorgan Branch" },
    { value: "Goldsboro-Greensboro" },
    { value: "Guyandot River Branch" },
    { value: "Havelock-Marine Jct" },
    { value: "High Point-Asheboro" },
    { value: "Hyco Spur" },
    { value: "Jacobs Fork Branch" },
    { value: "Jamboree Spur" },
    { value: "Kenova Belt Line" },
    { value: "Kenova" },
    { value: "Lee Creek-Chocowinity" },
    { value: "Lenore Branch" },
    { value: "Levisa Branch" },
    { value: "Long Fork Spur" },
    { value: "Mackeys-Cumnock" },
    { value: "Manassas-Edinburg" },
    { value: "Mate Creek Branch" },
    { value: "Mayo Creek Spur" },
    { value: "Montview-Salisbury" },
    { value: "Morehead City-Goldsboro" },
    { value: "Morri Branch" },
    { value: "Norfolk Terminal" },
    { value: "Norfolk" },
    { value: "Oxford-East Durham" },
    { value: "Pardee Branch" },
    { value: "Pine Branch" },
    { value: "Pinnacle Creek Branch" },
    { value: "Pocahontas" },
    { value: "Pomona-Rural Hall" },
    { value: "Potts Valley Branch" },
    { value: "Princeton-Deepwater" },
    { value: "Pulaski" },
    { value: "Richmond" },
    { value: "Right Fork Beech Fork" },
    { value: "Roanoke Terminal" },
    { value: "Roanoke" },
    { value: "Salisbury-Albemarle" },
    { value: "Salisbury-Greenville" },
    { value: "Salisbury-Murphy Jct" },
    { value: "Sand Lick Branch" },
    { value: "Sanford-Pomona" },
    { value: "Sidney Spur" },
    { value: "South Fork Branch" },
    { value: "St. Charles Branch" },
    { value: "Stokesland-Spray" },
    { value: "Stone Coal Branch" },
    { value: "Tug Fork Branch" },
    { value: "Upper Elk Creek Spur" },
    { value: "Varina-Fayetteville" },
    { value: "Wayne Branch" },
    { value: "West Virginia Secondary" },
    { value: "Whitethorne" },
    { value: "Winding Gulf Branch" },
    { value: "Winston Salem" },
    { value: "Winston-Salem-Charlotte" },
    { value: "Wolf Creek Branch" },
  ],
  Coastal: [
    { value: "Albany" },
    { value: "Anderson-Walhalla" },
    { value: "Atlanta North" },
    { value: "Atlanta South" },
    { value: "Augusta" },
    { value: "Brunswick" },
    { value: "C&G Jct-Piedmont" },
    { value: "CGA Columbus" },
    { value: "Camak" },
    { value: "Cedartown" },
    { value: "Central Of Georgia" },
    { value: "Charleston-Columbia" },
    { value: "Charlotte-Columbia" },
    { value: "Columbia-Augusta" },
    { value: "Columbia-Beaumont" },
    { value: "Columbia-Edmund" },
    { value: "Columbus" },
    { value: "Donaldson Jct-Michelin" },
    { value: "Dublin" },
    { value: "Eatonton" },
    { value: "Fairbanks" },
    { value: "Greenville-Inman" },
    { value: "Griffin" },
    { value: "Krannert" },
    { value: "Lula - Watkinsville" },
    { value: "Macon" },
    { value: "Madison" },
    { value: "Moores" },
    { value: "Navair" },
    { value: "Norcross" },
    { value: "Prosperity-Conrad" },
    { value: "Salisbury-Greenville" },
    { value: "Savannah" },
    { value: "Spartanburg-Campobello" },
    { value: "Thomaston" },
    { value: "Tirza-Kershaw" },
    { value: "Valdosta" },
    { value: "Washburn-Kings Creek" },
    { value: "Winston-Salem-Charlotte" },
  ],
  "Great Lakes": [
    { value: "(Gary Branch)" },
    { value: "CR & I IT" },
    { value: "Chicago B" },
    { value: "Chicago" },
    { value: "Chicago-Lake" },
    { value: "Cleveland" },
    { value: "Cleveland-Toledo" },
    { value: "Detroit Huntington" },
    { value: "Detroit" },
    { value: "Fort Wayne" },
    { value: "Fostoria" },
    { value: "Kankakee Branch" },
    { value: "Kankakee" },
    { value: "Lima" },
    { value: "Miami Cut" },
    { value: "Michigan" },
    { value: "New Castle" },
    { value: "Sandusky" },
    { value: "Stanley" },
    { value: "Toledo Belt Connecting" },
    { value: "Toledo" },
    { value: "Toledo-DBN" },
    { value: "Toledo-Elkhart" },
  ],
  Gulf: [
    { value: "3B North" },
    { value: "3B South" },
    { value: "AGS North" },
    { value: "AGS South" },
    { value: "Anniston" },
    { value: "Apollo" },
    { value: "Appalachia" },
    { value: "Autauga Creek" },
    { value: "Bell" },
    { value: "Berry Branch" },
    { value: "CNOTP South" },
    { value: "Central Of Georgia" },
    { value: "Chattanooga Terminal" },
    { value: "Cohutta" },
    { value: "Demopolis" },
    { value: "EG Line" },
    { value: "East End" },
    { value: "Jackson" },
    { value: "Knoxville West End" },
    { value: "Knoxville-BL" },
    { value: "Knoxville-Bristol" },
    { value: "Knoxville-Jellico" },
    { value: "Knoxville-K and A" },
    { value: "Knoxville-Middlesboro" },
    { value: "Knoxville-Oakdale" },
    { value: "Knoxville-River" },
    { value: "Memphis East End" },
    { value: "Memphis West End" },
    { value: "NO and NE" },
    { value: "New Orleans Terminal" },
    { value: "North Alabama West End" },
    { value: "Pulaski" },
    { value: "Salisbury-Murphy Jct" },
  ],
  Keystone: [
    { value: "(Bear Creek RT)" },
    { value: "(Harriman IT)" },
    { value: "(Lititz Sec)" },
    { value: "(Middle Brook IT)" },
    { value: "(Nave-Croxton RT)" },
    { value: "(Newark IT)" },
    { value: "(Parksburg IT)" },
    { value: "(Passaic Spur)" },
    { value: "(President St Tk)" },
    { value: "(Sparrows Point IT)" },
    { value: "(Suffern IT)" },
    { value: "(Wilmington & Northern RT)" },
    { value: "Altoona" },
    { value: "BX" },
    { value: "Buffalo" },
    { value: "C & F" },
    { value: "Captina" },
    { value: "Cement" },
    { value: "Cleveland-Pit" },
    { value: "Cloggsville" },
    { value: "Conemaugh" },
    { value: "Corning" },
    { value: "Cove" },
    { value: "Dale" },
    { value: "Ellsworth" },
    { value: "Fort Wayne-Pit" },
    { value: "Freight" },
    { value: "Hagerstown" },
    { value: "Harrisburg" },
    { value: "Ithaca" },
    { value: "Keystone" },
    { value: "Koppel" },
    { value: "Lake Erie" },
    { value: "Lake Erie-DBN" },
    { value: "Lehigh Sec" },
    { value: "Lehigh" },
    { value: "Lordstown" },
    { value: "Loveridge" },
    { value: "Lurgan" },
    { value: "Manassas-Edinburg" },
    { value: "Meadville" },
    { value: "Miracle Run" },
    { value: "Mon" },
    { value: "Morrisville" },
    { value: "New Castle Sec" },
    { value: "New Holland" },
    { value: "Newell Branch" },
    { value: "Niles" },
    { value: "Norristown" },
    { value: "Pittsburgh HB" },
    { value: "Pittsburgh" },
    { value: "Port Perry" },
    { value: "Port Road" },
    { value: "Portland" },
    { value: "Pottsville" },
    { value: "Reading" },
    { value: "Reybold Branch" },
    { value: "River" },
    { value: "Royalton" },
    { value: "Shellpot" },
    { value: "Shippensburg" },
    { value: "South Fork" },
    { value: "Southern Tier Pitt" },
    { value: "Southern Tier" },
    { value: "Stroudsburg" },
    { value: "Sunbury" },
    { value: "Washington" },
    { value: "Watsontown" },
    { value: "Waynesburg Southern" },
    { value: "Weirton" },
    { value: "Youngstown" },
  ],
  Midwest: [
    { value: "Alton A&E" },
    { value: "Alton T&E" },
    { value: "Bloomington" },
    { value: "Brooklyn" },
    { value: "CNOTP North" },
    { value: "Cairo Branch" },
    { value: "Cincinnati Terminal" },
    { value: "Cincinnati" },
    { value: "Dayton" },
    { value: "Decatur Terminal" },
    { value: "Evansville Branch" },
    { value: "Frankfort Branch" },
    { value: "Frankfort" },
    { value: "Kansas City" },
    { value: "Lafayette" },
    { value: "Louisville" },
    { value: "Madison Branch" },
    { value: "Mansfield Branch" },
    { value: "Marion Branch" },
    { value: "Meredosia Branch" },
    { value: "Monterey Branch" },
    { value: "New Castle" },
    { value: "Red Key Secondary" },
    { value: "Rockport Branch" },
    { value: "Southern-East" },
    { value: "Southern-West" },
    { value: "Springfield-Hannibal" },
    { value: "St Louis" },
    { value: "V&C Belt" },
    { value: "Yankeetown Branch" },
  ],
};

export const CpkcSouthSubdivisions = [
  { value: "Kansas City" },
  { value: "Mexico" },
  { value: "Roodhouse" },
  { value: "Springfield" },
  { value: "Jacksonville" },
  { value: "Godfrey" },
  { value: "East St. Louis Terminal" },
  { value: "Gateway Eastern Branch" },
  { value: "Pittsburg" },
  { value: "Heavener" },
  { value: "Fort Smith Branch" },
  { value: "Shreveport" },
  { value: "Shreveport Terminal" },
  { value: "Greenville" },
  { value: "Alliance" },
  { value: "Dallas" },
  { value: "White Rock Branch" },
  { value: "Vicksburg" },
  { value: "Hodge" },
  { value: "Redwood Branch" },
  { value: "Meridian" },
  { value: "Haverty" },
  { value: "Bay Springs" },
  { value: "Branch" },
  { value: "Artesia" },
  { value: "Louisville Connection" },
  { value: "Tuscaloosa" },
  { value: "Aberdeen Branch" },
  { value: "Counce Branch" },
  { value: "Yellow Creek Branch" },
  { value: "Gulfport" },
  { value: "Alexandria" },
  { value: "New Orleans" },
  { value: "Beaumont" },
  { value: "Lake Charles" },
  { value: "Rosenberg" },
  { value: "Laredo" },
  { value: "Port Neches Belt Line" },
  { value: "Port Neches Branch" },
];

export const timezonesDropdownArray = [
  {
    value: "America/Chicago",
  },
  {
    value: "America/Denver",
  },
  {
    value: "America/Los_Angeles",
  },
  {
    value: "America/New_York",
  },
];

export const tracksByOrgId = {
  2: [
    { value: "BRANCH (B)" },
    { value: "MAIN" },
    { value: "MT 5" },
    { value: "MT 6" },
    { value: "MT 7" },
    { value: "MT 8" },
    { value: "I" },
  ],
  94: [
    { value: "BRANCH (B)" },
    { value: "MAIN" },
    { value: "MT 5" },
    { value: "MT 6" },
    { value: "MT 7" },
    { value: "MT 8" },
    { value: "I" },
  ],
  106: [
      { value: "BRANCH (B)" },
      { value: "MAIN" },
      { value: "MT 5" },
      { value: "MT 6" },
      { value: "MT 7" },
      { value: "MT 8" },
      { value: "I" },
    ],
  6: [
    { value: "CNRT" },
    { value: "CROS" },
    { value: "INDL" },
    { value: "INDU" },
    { value: "SIDE" },
    { value: "MAIN" },
    { value: "MLXO" },
    { value: "NO 1" },
    { value: "NO 2" },
    { value: "NO 3" },
    { value: "NO 4" },
    { value: "NO 5" },
    { value: "NO 6" },
    { value: "YARD" },
  ],
  22: [{ value: "MAIN1" }],
};
